# @package _global_
# Hyperparameter grid for pretraining on 100 synthetic datasets (moderate model)
model:
  dynamic_causal_pfn:
    tune_hparams: True
    tune_range: 20
    hparams_grid:
      num_layer:
        - 2
        - 4
        - 6
      num_heads:
        - 2
        - 4
      learning_rate:
        - 0.001
        - 0.0005
      batch_size:
        - 128
        - 256
      seq_hidden_units:
        - 8
        - 16
        - 32
      hr_size:
        - 8
        - 16
        - 32
      fc_hidden_units:
        - 2
        - 4
        - 8
      dropout_rate:
        - 0.1
        - 0.2
    resources_per_trial:
      cpu: 0.5
      gpu: 0.5

exp:
  max_epochs: 20
