# @package _global_
dataset:
  coeff: 10.0
  fill_missing: False

model:
  encoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 128
    seq_hidden_units: 15
    br_size: 20
    fc_hidden_units: 80
    dropout_rate: 0.2

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 256
    br_size: 10
    fc_hidden_units: 5
    seq_hidden_units: 20
    dropout_rate: 0.2

exp:
  weights_ema: False
  balancing: grad_reverse
  max_epochs: 50
