"""
Pre-training dataset generation for DynamicCausalPFN.

After pre-training on these datasets, 
we will evaluate DynamicCausalPFN's performance on cancer test dataset - zeroshot, fewshot, fine-tuning

Therefore, a large-scale of pre-training dataset is generated
baesd on DAG structure following cancer simulation data
(Time-varying covariate (prev_outcome (prev tumour volume)),
static_feature (patient types),
treatment (radiotherapy),
outcome (tumour volume)).

sequence_length = 30
projection_horizon = 2 (tau = 2 + 1 = 3)

At each timestep,
1) treatment is generated by treatment network given current covariate.
2) outcome is generated by outcome network given coviarate, treatment, static feature.

current outcome is then put into the next timestep's covariate.

And again generate treatment, outcome, .. and so on. 

Iterate this procedure to make timeseries of length = 30.

Given network parameters, noises, etc, a dataset is filled with M timeseries samples.

Do this for different parameters, and a large-scale dataset is generated. (N datasets).


We generate synthetic datasets (tasks) as follows. 
Each dataset is produced by:
- Sample ONE treatment network and ONE outcome network (fixed within the dataset).
- Generating M trajectories (samples), each of length T=seq_length.

DAG at each time step t:
	X_t -> A_t
	X_t -> Y_t
	A_t -> Y_t
	S    -> Y_t

	Dynamics:
		X_0 sampled from a realistic tumor-volume distribution
		For t=0...T-2:
			A_t ~ Bernoulli( sigmoid( f_A(X_t) ) )
			Y_t(a) = f_Y([X_t, a, S]) for a in {0, 1}
			Y_t = Y_t(A_t)
			X_{t+1} <- Y_t
	
	Outputs are aligned with cancer_simple.py keys:
		cancer_volume, radio_application, sequence_lengths, patient_types
	"""

from typing import Callable, Dict, Optional, Tuple

import numpy as np
import pandas as pd

MAX_VALUE = 100.0 

def _sample_initial_volumes(num_patients: int) -> np.ndarray:
	"""
	Sample initial tumour volumes 
	"""
	x0 = np.random.lognormal(mean=0.0, sigma=1.0, size=num_patients)
	x0 = np.clip(x0, 1e-3, None)#.astype(np.float64)
	
	return x0 


def _softplus(x: np.ndarray) -> np.ndarray:
	# numerically stable softplus
	return np.log1p(np.exp(-np.abs(x))) + np.maximum(x, 0.0)


def _sigmoid(x: np.ndarray) -> np.ndarray:
	return 1.0 / (1.0 + np.exp(-np.clip(x, -50, 50)))


# --------------------------------------------------------------------------------------
# Stochastic MLP primitives 
# --------------------------------------------------------------------------------------

class TreatmentAssigner:
	"""
	Stochastic propensity network:
		logit = f_A(X) with additive noise per layer,
		A ~ Bernoulli(sigmoid(logit))
	The sampled network parameters are FIXED for the whole dataset (task),
	but exogenous noise is sampled per call (per sample/time).
	"""

	def __init__(
			self, 
			prior_layers: Callable[[], int] = lambda: np.random.randint(2, 4), # (3, 5)
			prior_hidden_size: Callable[[], int] = lambda: np.random.randint(8, 30), # (8, 20)
			weight_std:float=1.0, # 0.8
			activation: Callable[[np.ndarray], np.ndarray] = np.tanh,
	):
		self.prior_layers=prior_layers
		self.prior_hidden_size=prior_hidden_size
		self.weight_std=weight_std
		self.activation=activation

		self.layer_weights: list[np.ndarray] = []
		self.layer_biases: list[np.ndarray] = []
		self.noise_samplers: list[Callable[[Tuple[int, int]], np.ndarray]] = []

		self.initialized: bool=False
		self.propensity_scores: Optional[np.ndarray] = None 
	
	def _sample_noise_distribution(self) -> Callable[[Tuple[int, int]], np.ndarray]:
		dist_type = np.random.choice(["normal", "uniform", "laplace", "logistic"])
		if dist_type == "normal":
			scale = np.random.uniform(0.05, 0.5) # (0.1, 1.0)
			return lambda shape: np.random.normal(0.0, scale, size=shape)
		if dist_type == "uniform":
			scale = np.random.uniform(0.05, 0.5) # (0.1, 1.0)
			return lambda shape: np.random.uniform(-scale, scale, size=shape)
		if dist_type == "laplace":
			scale = np.random.uniform(0.05, 0.3) # (0.1, 0.5)
			return lambda shape: np.random.laplace(0.0, scale, size=shape)
		# logistic
		scale = np.random.uniform(0.05, 0.3) # (0.1, 0.5)
		return lambda shape: np.random.logistic(0.0, scale, size=shape)
	
	def sample_new_mechanism(self, input_dim:int) -> None:
		depth = int(np.clip(self.prior_layers(), 2, 3)) # 3, 5
		hidden = int(self.prior_hidden_size())

		dims = [input_dim] + ([hidden] * (depth - 2)) + [1]

		self.layer_weights = []
		self.layer_biases = []
		self.noise_samplers = []

		for din, dout in zip(dims[:-1], dims[1:]):
			W = np.random.normal(0.0, self.weight_std / np.sqrt(max(din, 1)), size=(din, dout)) # normal(0.0, self.weight_std)
			b = np.random.normal(0.0, self.weight_std, size=(dout,))
			self.layer_weights.append(W)
			self.layer_biases.append(b)
			self.noise_samplers.append(self._sample_noise_distribution())
		
		self.initialized = True
	
	def _forward_logits(self, X: np.ndarray) -> np.ndarray:
		n = X.shape[0]
		h = X 
		for li, (W, b, noise_sampler) in enumerate(zip(self.layer_weights, self.layer_biases, self.noise_samplers)):
			eps = noise_sampler((n, W.shape[1]))
			h = h @ W + b + eps
			if li < len(self.layer_weights) - 1:
				h = self.activation(h)
		return h.reshape(-1)
	
	def generate_treatments(self, X: np.ndarray, resample: bool=False) -> np.ndarray:
		if (not self.initialized) or resample:
			self.sample_new_mechanism(input_dim=X.shape[1])
		
		logits = self._forward_logits(X)
		p = _sigmoid(logits)
		self.propensity_scores = p
		A = np.random.binomial(1, p)#.astype(np.int64)
		return A 
	

class OutcomeGenerator:
	"""
	Stochastic outcome network with edge-drop on hidden weights:
		Y(a) = f_Y([X, a, S]) with additive noise per layer
	Potential outcomes Y(0), Y(1) share the SAME sampled exogenous noise per call
	(per sample/time).
	"""
	def __init__(
			self, 
			prior_layers: Callable[[], int] = lambda: np.random.randint(2, 4), # (3, 6)
			prior_hidden_size: Callable[[], int] = lambda: np.random.randint(8, 30), # (10, 25)
			weight_std: float=1.0,
			edge_drop_prob: float=0.3,
			activation: Callable[[np.ndarray], np.ndarray] = np.tanh,
	):
		self.prior_layers=prior_layers
		self.prior_hidden_size=prior_hidden_size
		self.weight_std=weight_std
		self.edge_drop_prob=edge_drop_prob
		self.activation=activation


		self.layer_weights: list[np.ndarray] = []
		self.layer_biases: list[np.ndarray] = []
		self.noise_samplers: list[Callable[[Tuple[int, int]], np.ndarray]] = []

		self.initialized: bool=False

	
	def _sample_noise_distribution(self) -> Callable[[Tuple[int, int]], np.ndarray]:
		dist_type = np.random.choice(["normal", "uniform", "laplace", "logistic"])
		if dist_type == "normal":
			scale = np.random.uniform(0.05, 0.5) # (0.1, 1.0)
			return lambda shape: np.random.normal(0.0, scale, size=shape)
		if dist_type == "uniform":
			scale = np.random.uniform(0.05, 0.5) # (0.1, 1.0)
			return lambda shape: np.random.uniform(-scale, scale, size=shape)
		if dist_type == "laplace":
			scale = np.random.uniform(0.05, 0.3) # (0.1, 0.5)
			return lambda shape: np.random.laplace(0.0, scale, size=shape)
		scale = np.random.uniform(0.05, 0.3) # (0.1, 0.5)
		return lambda shape: np.random.logistic(0.0, scale, size=shape)
	
	def sample_new_mechanism(self, input_dim:int) -> None:
		depth = int(np.clip(self.prior_layers(), 2, 3)) # 3, 6
		hidden = int(self.prior_hidden_size())

		dims = [input_dim] + ([hidden] * (depth - 2)) + [1]

		self.layer_weights = []
		self.layer_biases = []
		self.noise_samplers = []

		for li, (din, dout) in enumerate(zip(dims[:-1], dims[1:])):
			W = np.random.normal(0.0, self.weight_std / np.sqrt(max(din, 1)), size=(din, dout)) # normal(0.0, self.weight_std)

			# Drop edges for hidden layers only (not outout layer)
			if self.edge_drop_prob > 0.0 and li < len(dims) - 2:
				mask = (np.random.rand(*W.shape) > self.edge_drop_prob).astype(W.dtype)
				W = W * mask 
			
			b = np.random.normal(0.0, self.weight_std, size=(dout,))
			self.layer_weights.append(W)
			self.layer_biases.append(b)
			self.noise_samplers.append(self._sample_noise_distribution())
		
		self.initialized = True
	
	def _forward_raw(self, Z: np.ndarray, noise_list: Optional[list[np.ndarray]] = None) -> Tuple[np.ndarray, list[np.ndarray]]:
		n = Z.shape[0]
		h = Z
		used_noise: list[np.ndarray] = []

		for li, (W, b, noise_sampler) in enumerate(zip(self.layer_weights, self.layer_biases, self.noise_samplers)):
			eps = noise_sampler((n, W.shape[1])) if noise_list is None else noise_list[li]
			used_noise.append(eps)

			h = h @ W + b + eps
			if li < len(self.layer_weights) - 1:
				h = self.activation(h)
		
		return h.reshape(-1), used_noise
	
	def _to_volume(self, raw: np.ndarray) -> np.ndarray:
		vol = _softplus(raw) 
		vol = np.clip(vol, 0.0, MAX_VALUE)
		return vol 
	
	def generate_outcomes(
			self, 
			X: np.ndarray,
			A: np.ndarray,
			S: np.ndarray,
			resample: bool = False,
	) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
		"""
		Args:
			X: (n, dx)
			A: (n,) int {0, 1}
			S: (n, ds)
		Returns:
			Y: (n,) factual
			Y0: (n,) potential under 0
			Y1: (n,) potential under 1
		"""
		if (not self.initialized) or resample:
			input_dim = X.shape[1] + 1 + S.shape[1]
			self.sample_new_mechanism(input_dim=input_dim)
		
		n = X.shape[0]
		a0 = np.zeros((n, 1), dtype=X.dtype)
		a1 = np.ones((n, 1), dtype=X.dtype)

		z0 = np.concatenate([X, a0, S], axis=1)
		z1 = np.concatenate([X, a1, S], axis=1)

		# Shared exogenous noise between Y(0) and Y(1) per sample/time
		_, noise = self._forward_raw(z0, noise_list=None)
		raw0, _ = self._forward_raw(z0, noise_list=noise)
		raw1, _ = self._forward_raw(z1, noise_list=noise)

		y0 = self._to_volume(raw0)
		y1 = self._to_volume(raw1)
		y = np.where(A.astype(bool), y1, y0)

		return y, y0, y1 
	

# --------------------------------------------------------------------------------------
# Main generator (aligned with cancer_simple.py outputs)
# --------------------------------------------------------------------------------------

def generate_pretraining_dataset(
		num_samples: int,
		seq_length: int,
		*,
		seed: Optional[int] = None,
		treatment_assigner: Optional[TreatmentAssigner] = None,
		outcome_generator: Optional[OutcomeGenerator] = None,
		initial_volume_sampler: Optional[Callable[[int], np.ndarray]] = None,
		patient_type_sampler: Optional[Callable[[int], np.ndarray]] = None,
) -> Dict[str, np.ndarray]:
	"""
	Generate ONE synthetic dataset (one task) with num_samples trajectories.
	
	- A single treatment network and outcome network is sampled once and reused.
	- At each t:
		A_t sampled from treatment net given current covariate X_t
		Y_t sampled from outcome net given X_t, A_t, S
	
	Returns dict compatible with cancer_simple.py consumers.
	"""

	if seed is not None:
		np.random.seed(seed)
	
	# Sample patient-level static features and initial volumes
	if initial_volume_sampler is None:
		initial_volumes = _sample_initial_volumes(num_samples)
	else:
		initial_volumes = initial_volume_sampler(num_samples)
	
	if patient_type_sampler is None:
		patient_types = np.random.choice([1, 2, 3], size=num_samples)
	else:
		patient_types = patient_type_sampler(num_samples)
	
	# Static feature tensor S (n, ds). Keep ds=1 for alignment (patient_types as scalar).
	# S = patient_types.astype(np.float32).reshape(-1, 1)
	S = patient_types.reshape(-1, 1)

	# Create / sample mechanisms (fixed within this dataset)
	if treatment_assigner is None:
		treatment_assigner = TreatmentAssigner()
	if outcome_generator is None:
		outcome_generator = OutcomeGenerator()
	
	# Covariate is previous cancer volume => dx=1
	treatment_assigner.sample_new_mechanism(input_dim=1)
	outcome_generator.sample_new_mechanism(input_dim=1 + 1 + S.shape[1])

	# Allocate outputs (same style as cancer_simple)
	cancer_volume = np.zeros((num_samples, seq_length))#, dtype=np.float32)
	radio_application = np.zeros((num_samples, seq_length))#, dtype=np.int8)

	sequence_lengths = np.full((num_samples,), seq_length)#, dtype=np.int32)

	# Set initial covariate at t=0
	cancer_volume[:, 0] = initial_volumes#.astype(np.float32)

	for i in range(num_samples):
		for t in range(seq_length):
			X_t = cancer_volume[i, t].reshape(-1, 1)

			# Treatment at time t
			A_t = treatment_assigner.generate_treatments(X_t, resample=False)

			# radio_application[i, t] = np.int8(A_t[0])
			radio_application[i, t] = A_t[0]

			# current outcome becomes next covariate
			if t < seq_length - 1:
				S_i = S[i:i+1]
				y_next, _, _ = outcome_generator.generate_outcomes(X_t, A_t, S_i, resample=False)
				# cancer_volume[i, t+1] = np.float32(y_next[0])
				cancer_volume[i, t+1] = y_next[0]

	outputs = {
		"cancer_volume": cancer_volume,
		"radio_application": radio_application,
		"sequence_lengths": sequence_lengths,
		"patient_types": patient_types,
	}

	return outputs


def get_pretrain_scaling_params(sim: Dict[str, np.ndarray]) -> Tuple[pd.Series, pd.Series]:
	
	means = {}
	stds = {}
	
	means['cancer_volume'] = np.mean(sim['cancer_volume'])
	stds['cancer_volume'] = np.std(sim['cancer_volume'])

	# Add means for static variables
	means['patient_types'] = np.mean(sim['patient_types'])
	stds['patient_types'] = np.std(sim['patient_types'])

	return pd.Series(means), pd.Series(stds)


# Generate N datasets (tasks)
def generate_many_pretraining_datasets(
		num_datasets: int,
		samples_per_dataset: int,
		seq_length: int,
		*, 
		base_seed: Optional[int] = None,
		**kwargs,
) -> list[Dict[str, np.ndarray]]:
	"""
	Returns a list of datasets [D_0, ..., D_{N-1}], each generated with a different mechanism.
	Useful if PFN training samples "a dataset/task" per batch element.
	"""
	out = []
	for i in range(num_datasets):
		seed_i = None if base_seed is None else base_seed + i
		ds = generate_pretraining_dataset(
			samples_per_dataset, 
			seq_length, 
			seed=seed_i, 
			**kwargs,
		)
		out.append(ds)
	return out 



# Main execution
if __name__ == "__main__":
    # Generate 10k datasets with 1024 samples each
    datasets = generate_many_pretraining_datasets(
        num_datasets=10000,
        samples_per_dataset=1024,
        seq_length=30,
        base_seed=42
    )